name: Deploy on Merge

on:
  push:
    branches:
      - main
jobs:
    deploy-to-snowflake:
        name: Build and deploy Docker image to Snowflake
        runs-on: ubuntu-latest
        
        env:
            IMAGE_NAME: trip_analytics_app
            STAGE_NAME: SNOWFLAKE.DEFAULT_IMAGE_STORE.ML_REPO
            STAGE_NAME_LOWER: snowflake/default_image_store/ml_repo
            SNOWFLAKE_ACCOUNT: ${{ secrets.SNOWFLAKE_ACCOUNT_NAME }}
            SNOWFLAKE_USER: ${{ secrets.SNOWFLAKE_USER }}
            SNOWFLAKE_PASSWORD: ${{ secrets.SNOWFLAKE_PASSWORD }}
            SNOWFLAKE_ROLE: ${{ secrets.SNOWFLAKE_ROLE }}
            SNOWFLAKE_AUTHENTICATOR: password

        steps:
        - name: Checkout code
          uses: actions/checkout@v4
        
        - name: Set up Docker Buildx
          uses: docker/setup-buildx-action@v3

        - name: Set up Snowflake CLI
          uses: snowflakedb/snowflake-cli-action@v2.0
          with:
                cli-version: "3.11.0"

        - name: Add Snowflake connection
          run: |
                snow connection add \
                --connection-name test_connection \
                --accountname ${{ secrets.SNOWFLAKE_ACCOUNT_NAME}} \
                --username ${{ secrets.SNOWFLAKE_USER }} \
                --password ${{ secrets.SNOWFLAKE_PASSWORD }} \
                --role ${{ secrets.SNOWFLAKE_ROLE }} \
                --warehouse X-Small \
                --database snowflake \
                --schema default_image_store \
                --host qmwkxar-ob52901.snowflakecomputing.com \
                --region eu-north-1 \
                --authenticator snowflake \
                --no-interactive \
                --default

        - name: Login to Snowflake Image Registry
          run: |
                snow spcs image-registry login --connection test_connection

        - name: Build Docker image
          run: |
            docker build --no-cache -t $IMAGE_NAME .

        - name: Tag Docker image
          run: |
            docker tag $IMAGE_NAME ${{ env.SNOWFLAKE_ACCOUNT }}.registry.snowflakecomputing.com/${{ env.STAGE_NAME_LOWER }}:latest


        - name: Get Snowflake Registry URL
          id: get_registry_url
          run: |
            REGISTRY_URL=$(snow spcs image-registry url --connection test_connection)
            echo "::set-output name=registry_url::$REGISTRY_URL"



        - name: Docker login
          run: |
           docker login ${{ steps.get_registry_url.outputs.registry_url }} \
            -u _token \
            -p "$(snow spcs image-registry token --connection test_connection)"


        - name: Push Docker Image to Snowflake Stage
          run: |
            docker push ${{ env.SNOWFLAKE_ACCOUNT }}.registry.snowflakecomputing.com/${{ env.STAGE_NAME_LOWER }}

