name: Deploy on Merge

on:
  push:
    branches:
      - main
jobs:
    deploy-to-snowflake:
        name: Build and deploy Docker image to Snowflake
        runs-on: ubuntu-latest
        
        env:
            IMAGE_NAME: trip_analytics_app
            STAGE_NAME: SNOWFLAKE.DEFAULT_IMAGE_STORE.ML_REPO
            STAGE_NAME_LOWER: snowflake/default_image_store/ml_repo
            SNOWFLAKE_ACCOUNT: ${{ secrets.SNOWFLAKE_ACCOUNT_NAME }}
            SNOWFLAKE_USER: ${{ secrets.SNOWFLAKE_USER }}
            SNOWFLAKE_PASSWORD: ${{ secrets.SNOWFLAKE_PASSWORD }}
            SNOWFLAKE_ROLE: ${{ secrets.SNOWFLAKE_ROLE }}

        steps:
        - name: Checkout code
          uses: actions/checkout@v4
        
        - name: Set up Docker Buildx
          uses: docker/setup-buildx-action@v3

        - name: Set up Snowflake CLI
          uses: snowflakedb/snowflake-cli-action@v2.0
          with:
                cli-version: "3.11.0"

        - name: Build Docker image
          run: |
            docker build --no-cache -t $IMAGE_NAME .

        - name: Tag Docker image
          run: |
            docker tag $IMAGE_NAME ${{ env.SNOWFLAKE_ACCOUNT }}.registry.snowflakecomputing.com/${{ env.STAGE_NAME_LOWER }}:latest

        - name: Add Snowflake connection, login to image registry and push Docker image
          run: |
                snow connection add \
                --connection-name github_ci_connection \
                --accountname ${{ env.SNOWFLAKE_ACCOUNT }} \
                --username ${{ env.SNOWFLAKE_USER }} \
                --password ${{ env.SNOWFLAKE_PASSWORD }} \
                --role ${{ env.SNOWFLAKE_ROLE }} \
                --warehouse X-Small \
                --database snowflake \
                --schema default_image_store \
                --host qmwkxar-ob52901.snowflakecomputing.com \
                --region eu-north-1 \
                --authenticator snowflake \
                --no-interactive \
                --default
                snow spcs image-registry login
                docker push ${{ env.SNOWFLAKE_ACCOUNT }}.registry.snowflakecomputing.com/${{ env.STAGE_NAME_LOWER }}:latest
