name: Deploy on Merge

on:
  push:
    branches:
      - main
jobs:
    deploy-to-snowflake:
        name: Build and deploy Docker image to Snowflake
        runs-on: ubuntu-latest
        
        env:
            IMAGE_NAME: trip_analytics_app
            STAGE_NAME: OPS.SPCS_DEPLOYMENT.TRIP_ANALYTICS_CONTAINER_STAGE
            STAGE_NAME_LOWER: ops.spcs_deployment.trip_analytics_container_stage
            SNOWFLAKE_ACCOUNT: ${{ secrets.SNOWFLAKE_ACCOUNT_NAME }}
            SNOWFLAKE_USER: ${{ secrets.SNOWFLAKE_USER }}
            SNOWFLAKE_PASSWORD: ${{ secrets.SNOWFLAKE_PASSWORD }}
            SNOWFLAKE_ROLE: ${{ secrets.SNOWFLAKE_ROLE }}
            SNOWFLAKE_AUTHENTICATOR: password

        steps:
        - name: Checkout code
          uses: actions/checkout@v4
        
        - name: Set up Docker Buildx
          uses: docker/setup-buildx-action@v3

        - name: Set up Snowflake CLI
          uses: snowflakedb/snowflake-cli-action@v2.0
          with:
                cli-version: "3.11.0"

        - name: Build Docker image
          run: |
            docker build --no-cache -t $IMAGE_NAME .

        - name: Tag Docker image
          run: |
            docker tag $IMAGE_NAME snowflake_registry/${{ env.STAGE_NAME_LOWER }}/$IMAGE_NAME:latest

        - name: Push Docker Image to Snowflake Stage
          run: |
            snow image push --image-name $IMAGE_NAME --stage $STAGE_NAME --tag latest